apiVersion: v2
name: onecx-bookmark-svc
version: 0.0.0
appVersion: 0.0.0
description: Onecx bookmark service
keywords:
  - bookmark
sources:
  - https://github.com/onecx/onecx-bookmark-svc
maintainers:
  - name: Tkit Developer
    email: tkit_dev@1000kit.org
dependencies:
  - name: helm-quarkus-app
    alias: app
    version: 0.42.0
    repository: oci://ghcr.io/onecx/charts